#.travis.yml

sudo: required
services:
  - docker

before_install:
  - docker build -t coralgo/multi-docker-client -f Dockerfile.dev .

script:
  - docker run coralgo/multi-docker-client npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker-client"
  env: "MultiDockerClient-env"
  bucket_name: "elasticbeanstalk-eu-central-1-054632996260"
  bucket_path: "multi-docker-client"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
